### ISSUE TITLE
How to add a new arcaea account?

### ISSUE THREAD

**Issue by kirainmoe** [TheSnowfield/BotArcAPI#5]
Hello, I just found this project and I met the following error:
```
{
  status: -2,
  message: "allocate an arc account failed"
}
```
After reading the code I guess that I may need to add a new arcaea account to arcaccount.db. However I didn't find any related API in v1 or v2, and I don't know what are the meanings of `device`, `ucode` and `token` in the `arcaccount.account` table. 

Can someone explains that how to add a new arcaea account to the database, or is there any other way to solve the "sllocate an arc account failed" error?

**Comment by TheSnowfield** [comment]
I am not documented about how to register the new arc account via arcapi, I think its not good for 616.
but I can explain u every field means and how to add your arc account to database.

| field | explain |
| -- | -- |
| name | account username |
| passwd | account password |
| device | an id to specific a device, if u change it more than 3 times in one day, server will ban u 24 hours |
| uid | user id for delete your friend, maybe its an user index in 616 database |
| ucode | user code for add a friend |
| token | server authorization token for arcapis |
| banned | flag used to specific the account which is banned from 616

there is no public api to add your account to database due to safety reason. usually, u could just add the username and password into arcaccount database via any sqlite viewer/explorer/spy software. botarcapi will auto login your account and write ucode or token or another data back to the database. btw, sqlite will auto generate the device id by random hex if the device field you keep null in the sql.

have fun!

**Comment by kirainmoe** [comment]
Thank you for your quick reply! I will have a try.
